version: "3.4"


services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    container_name: notebook 
    env_file:
      - ./envs/db_keys
    volumes:
      - ./src:/src
    depends_on:
      - db
    command : ["sh", "-c", "gunicorn quickstart.wsgi -b 0.0.0.0:8000"]

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - ./envs/db_keys
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
      - /psql_db/postgres_data_backups:/backups

  adminer:
    image: adminer
    container_name: psql_admin
    ports:
      - "8080:8080"

  redis:
    image: redis:3.2-alpine
    container_name: cel_redis
    volumes:
      - ./redis_data:/data
